# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-22 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkvellir', '0002_remove_region_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='first_name',
            new_name='country_part',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='last_name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='name',
            new_name='country_part',
        ),
    ]
